#############################################################################
# Makefile for building: out/serialtool
# Generated by qmake (2.01a) (Qt 4.7.2) on: Fri Jun 17 22:12:22 2011
# Project:  serialtool.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -o Makefile serialtool.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m32 -march=i686 -mtune=atom -fasynchronous-unwind-tables -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -Isrc -Iout -Iout
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)   -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = out/

####### Files

SOURCES       = src/comtoolmain.cpp \
		src/serialtool.cpp out/moc_myqcombobox.cpp \
		out/moc_myqlineedit.cpp \
		out/moc_serialtool.cpp \
		out/qrc_myresource.cpp
OBJECTS       = out/comtoolmain.o \
		out/serialtool.o \
		out/moc_myqcombobox.o \
		out/moc_myqlineedit.o \
		out/moc_serialtool.o \
		out/qrc_myresource.o
DIST          = /usr/lib/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/release.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf \
		serialtool.pro
QMAKE_TARGET  = serialtool
DESTDIR       = out/
TARGET        = out/serialtool

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): out/ui_serialtool.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) out/ || $(MKDIR) out/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: serialtool.pro  /usr/lib/qt4/mkspecs/linux-g++/qmake.conf /usr/lib/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib/qt4/mkspecs/common/unix.conf \
		/usr/lib/qt4/mkspecs/common/linux.conf \
		/usr/lib/qt4/mkspecs/qconfig.pri \
		/usr/lib/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/lib/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib/qt4/mkspecs/features/qt_config.prf \
		/usr/lib/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt4/mkspecs/features/default_pre.prf \
		/usr/lib/qt4/mkspecs/features/release.prf \
		/usr/lib/qt4/mkspecs/features/default_post.prf \
		/usr/lib/qt4/mkspecs/features/warn_on.prf \
		/usr/lib/qt4/mkspecs/features/qt.prf \
		/usr/lib/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib/qt4/mkspecs/features/moc.prf \
		/usr/lib/qt4/mkspecs/features/resources.prf \
		/usr/lib/qt4/mkspecs/features/uic.prf \
		/usr/lib/qt4/mkspecs/features/yacc.prf \
		/usr/lib/qt4/mkspecs/features/lex.prf
	$(QMAKE) -o Makefile serialtool.pro
/usr/lib/qt4/mkspecs/common/g++-multilib.conf:
/usr/lib/qt4/mkspecs/common/unix.conf:
/usr/lib/qt4/mkspecs/common/linux.conf:
/usr/lib/qt4/mkspecs/qconfig.pri:
/usr/lib/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/lib/qt4/mkspecs/features/qt_functions.prf:
/usr/lib/qt4/mkspecs/features/qt_config.prf:
/usr/lib/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt4/mkspecs/features/default_pre.prf:
/usr/lib/qt4/mkspecs/features/release.prf:
/usr/lib/qt4/mkspecs/features/default_post.prf:
/usr/lib/qt4/mkspecs/features/warn_on.prf:
/usr/lib/qt4/mkspecs/features/qt.prf:
/usr/lib/qt4/mkspecs/features/unix/thread.prf:
/usr/lib/qt4/mkspecs/features/moc.prf:
/usr/lib/qt4/mkspecs/features/resources.prf:
/usr/lib/qt4/mkspecs/features/uic.prf:
/usr/lib/qt4/mkspecs/features/yacc.prf:
/usr/lib/qt4/mkspecs/features/lex.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile serialtool.pro

dist: 
	@$(CHK_DIR_EXISTS) out/serialtool1.0.0 || $(MKDIR) out/serialtool1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) out/serialtool1.0.0/ && $(COPY_FILE) --parents src/myqcombobox.h src/myqlineedit.h src/serialtool.h out/serialtool1.0.0/ && $(COPY_FILE) --parents ui/myresource.qrc out/serialtool1.0.0/ && $(COPY_FILE) --parents src/comtoolmain.cpp src/serialtool.cpp out/serialtool1.0.0/ && $(COPY_FILE) --parents ui/serialtool.ui out/serialtool1.0.0/ && (cd `dirname out/serialtool1.0.0` && $(TAR) serialtool1.0.0.tar serialtool1.0.0 && $(COMPRESS) serialtool1.0.0.tar) && $(MOVE) `dirname out/serialtool1.0.0`/serialtool1.0.0.tar.gz . && $(DEL_FILE) -r out/serialtool1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: out/moc_myqcombobox.cpp out/moc_myqlineedit.cpp out/moc_serialtool.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) out/moc_myqcombobox.cpp out/moc_myqlineedit.cpp out/moc_serialtool.cpp
out/moc_myqcombobox.cpp: src/myqcombobox.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/myqcombobox.h -o out/moc_myqcombobox.cpp

out/moc_myqlineedit.cpp: src/myqlineedit.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/myqlineedit.h -o out/moc_myqlineedit.cpp

out/moc_serialtool.cpp: out/ui_serialtool.h \
		src/serialtool.h
	/usr/lib/qt4/bin/moc $(DEFINES) $(INCPATH) src/serialtool.h -o out/moc_serialtool.cpp

compiler_rcc_make_all: out/qrc_myresource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) out/qrc_myresource.cpp
out/qrc_myresource.cpp: ui/myresource.qrc \
		ui/thank.png \
		ui/close.jpg \
		ui/erroring.png \
		ui/error.jpg \
		ui/success.png \
		ui/off.jpg \
		ui/network.jpg \
		ui/on.jpg
	/usr/lib/qt4/bin/rcc -name myresource ui/myresource.qrc -o out/qrc_myresource.cpp

compiler_image_collection_make_all: out/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) out/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: out/ui_serialtool.h
compiler_uic_clean:
	-$(DEL_FILE) out/ui_serialtool.h
out/ui_serialtool.h: ui/serialtool.ui \
		src/myqcombobox.h \
		src/myqlineedit.h
	/usr/lib/qt4/bin/uic ui/serialtool.ui -o out/ui_serialtool.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

out/comtoolmain.o: src/comtoolmain.cpp src/serialtool.h \
		out/ui_serialtool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/comtoolmain.o src/comtoolmain.cpp

out/serialtool.o: src/serialtool.cpp src/serialtool.h \
		out/ui_serialtool.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/serialtool.o src/serialtool.cpp

out/moc_myqcombobox.o: out/moc_myqcombobox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/moc_myqcombobox.o out/moc_myqcombobox.cpp

out/moc_myqlineedit.o: out/moc_myqlineedit.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/moc_myqlineedit.o out/moc_myqlineedit.cpp

out/moc_serialtool.o: out/moc_serialtool.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/moc_serialtool.o out/moc_serialtool.cpp

out/qrc_myresource.o: out/qrc_myresource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o out/qrc_myresource.o out/qrc_myresource.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

